'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { test } = require('node:test');
const ColorMath = require('../color-math.js');
const I = ColorMath._internal;
const html = fs.readFileSync(path.join(__dirname, '../index.html'), 'utf8');

// Evaluate the actual declarations from the shipped page. The DOM, browser
// events, network calls, and rendering are outside these numerical tests.
function declaration(name) {
  const match = html.match(new RegExp('^        function ' + name + '\\([^]*?^        }', 'm'));
  assert.ok(match, `Missing page function ${name}`);
  return match[0];
}
const platesSource = html.match(/var PLATES = \[[^]*?\n        \];/);
assert.ok(platesSource, 'Missing plate definitions');
const warnings = [];
const context = vm.createContext({
  ColorMath, window: {}, answers: [], calibrationWarning: false,
  console: { warn: message => warnings.push(message), info() {}, error: message => { throw Error(message); } },
});
vm.runInContext([
  declaration('labToHex'), platesSource[0], declaration('verifyPlates'),
  declaration('scoreResults'),
].join('\n'), context);
const plain = value => JSON.parse(JSON.stringify(value));
const plates = plain(context.PLATES);

// Published independent reference values, not outputs generated by ColorMath.
// Sharma, Wu & Dalal (2005), doi:10.1002/col.20070. Full provenance is in
// fixtures/README.md; the numerical test data are bundled for offline use.
const referencePairs = fs.readFileSync(path.join(__dirname, 'fixtures/ciede2000.txt'), 'utf8')
  .trim().split(/\r?\n/).map(line => line.trim().split(/\s+/).map(Number));
test('CIEDE2000 matches all 34 published reference pairs in both directions', () => {
  assert.equal(referencePairs.length, 34);
  for (const [index, row] of referencePairs.entries()) {
    assert.equal(row.length, 7);
    const first = row.slice(0, 3), second = row.slice(3, 6), expected = row[6];
    for (const [a, b] of [[first, second], [second, first]]) {
      const actual = I.deltaECiede2000(a, b);
      assert.ok(Math.abs(actual - expected) <= 0.00005, `Pair ${index + 1}: ${actual} != ${expected}`);
    }
    assert.equal(I.deltaECiede2000(first, first), 0);
  }
});

test('D65 neutral endpoints and hex/Lab round trips retain expected colors', () => {
  assert.deepEqual(I.hexToLab('#000000'), [0, 0, 0]);
  const white = I.hexToLab('#ffffff');
  assert.ok(Math.abs(white[0] - 100) < 0.0001);
  assert.ok(Math.abs(white[1]) < 0.0001 && Math.abs(white[2]) < 0.0001);
  assert.equal(context.labToHex(0, 0, 0), '#000000');
  assert.equal(context.labToHex(100, 0, 0), '#ffffff');
  for (const hex of ['#ff0000', '#00ff00', '#0000ff', '#808080', '#4a76bf']) {
    assert.equal(context.labToHex(...I.hexToLab(hex)), hex);
  }
});

test('14 plate definitions retain control, classifier, and luminance constraints', () => {
  assert.equal(plates.length, 14);
  assert.deepEqual(plates[0].tests, []);
  assert.notEqual(plates[0].fg.L, plates[0].bg.L);
  assert.equal(new Set(plates.map(p => p.seed)).size, 14);
  const categoryCounts = new Map();
  for (const [index, p] of plates.entries()) {
    assert.ok(['number', 'shape'].includes(p.type));
    assert.equal(p.correct.toLowerCase(), p.value.toLowerCase());
    assert.ok(Number.isInteger(p.seed));
    const category = p.tests.join(',');
    categoryCounts.set(category, (categoryCounts.get(category) || 0) + 1);
    for (const color of [p.fg, p.bg]) {
      for (const key of ['L', 'LR', 'a', 'aR', 'b', 'bR']) assert.ok(Number.isFinite(color[key]));
      for (const key of ['LR', 'aR', 'bR']) assert.ok(color[key] >= 0);
    }
    if (index > 0) {
      assert.equal(p.fg.L, p.bg.L, `Plate ${index + 1} luminance`);
      assert.equal(p.fg.LR, p.bg.LR, `Plate ${index + 1} luminance noise`);
      assert.ok(p.tests.length > 0);
    }
    for (const answer of p.nearMisses || []) assert.notEqual(answer, p.correct);
  }
  assert.deepEqual(Object.fromEntries(categoryCounts), {'': 1, 'protan,deutan': 5, tritan: 4, protan: 2, deutan: 2});
});

test('the existing simulated plate verifier reports no issues for all 14 plates', () => {
  const report = plain(context.verifyPlates(context.PLATES));
  assert.equal(report.length, 14);
  assert.equal(warnings.length, 0, warnings.join('\n'));
  for (const row of report) {
    assert.deepEqual(row.issues, [], `Plate ${row.plate}`);
    assert.ok(row.dE_normal >= 12);
    for (const target of row.tests) assert.ok(row['dE_' + target] <= 10);
  }
  assert.deepEqual(plain(context.window.__PLATE_VERIFICATION), report);
});

// Scenarios state expected behavior with canonical one-based plate numbers.
// They do not reimplement the scoring cascade. Control is always first, as in
// the page; only the screening plates are shuffled by the actual UI.
function score({ missed = [], near = [], calibration = false, reverse = false }) {
  const responses = plates.map((p, index) => ({
    plate: index, tests: p.tests,
    isCorrect: !missed.includes(index + 1) && !near.includes(index + 1),
    isNearMiss: near.includes(index + 1),
  }));
  if (reverse) responses.splice(1, 13, ...responses.slice(1).reverse());
  context.answers = responses;
  context.calibrationWarning = calibration;
  return plain(context.scoreResults());
}
const scenarios = [
  ['all correct', {}, 'normal'],
  ['calibration failure overrides clean answers', {calibration: true}, 'inconclusive'],
  ['control failure overrides every screening miss', {missed: Array.from({length:14}, (_,i) => i + 1)}, 'inconclusive'],
  ['one incorrect answer stays below threshold', {missed:[7]}, 'normal'],
  ['one near miss stays below threshold', {near:[7]}, 'normal'],
  ['two near misses precede classifier thresholds', {near:[7,12]}, 'anomalous'],
  ['two protan classifiers', {missed:[7,12]}, 'protan'],
  ['two deutan classifiers', {missed:[8,13]}, 'deutan'],
  ['one protan classifier and one screener do not assert subtype', {missed:[7,2]}, 'mild-red-green'],
  ['one protan classifier and two screeners corroborate subtype', {missed:[7,2,3]}, 'protan'],
  ['one classifier on each side avoids strong mixed label', {missed:[7,8]}, 'mild-red-green'],
  ['three classifier misses precede generic red-green', {missed:[7,8,12]}, 'red-green-mixed'],
  ['three general red-green screeners', {missed:[2,3,5]}, 'red-green'],
  ['three tritan plates', {missed:[4,6,10]}, 'tritan'],
  ['two red-green and one tritan', {missed:[2,3,4]}, 'multiple'],
  ['one red-green and one tritan', {missed:[2,4]}, 'mild-combined'],
  ['two general red-green screeners', {missed:[2,3]}, 'mild-red-green'],
  ['two tritan plates', {missed:[4,6]}, 'mild-tritan'],
];
for (const [name, input, expected] of scenarios) {
  test('scoring: ' + name, () => {
    const result = score(input);
    assert.equal(result.type, expected);
    assert.equal(result.rgTotal, 9);
    assert.equal(result.byTotal, 4);
    assert.deepEqual(score({...input, reverse:true}), result, 'screening order must not affect scoring');
  });
}
